### ISSUE TITLE
UI: Horizontal scrolling should have arrow / indicator to scroll

### ISSUE THREAD

**Issue by psyntium** [kedai-muslim/mobile-app#14]
floating < > at either end to show ada hidden items lagi...  kalau dah hujung, no arrow

**Comment by psyntium** [comment]
Done:
- Added left/right chevron to horizontal list

To be published in v0.1.2

**Comment by abasir** [comment]
The arrows are not clickable eh?
Also, should apply on all horizontal scroll on  any tab...

**Comment by psyntium** [comment]
Done:
- clickable left/right arrow

To be published in v0.1.2
