### ISSUE TITLE
UI: Incorrect 'features' by category

### ISSUE THREAD

**Issue by abasir** [kedai-muslim/mobile-app#7]
The features are the same (i.e., automotive features) regardless of category of shop.  Not sure data issue or UI issue.

**Comment by psyntium** [comment]
data from REST API seems ok. Checking UI

**Comment by psyntium** [comment]
if no features.. it'll fetch all features.. T_T

**Comment by psyntium** [comment]
Done:
- Default, features will include **-1** as id

will release in v0.1.1
